### PR TITLE
button styled added

### PR DESCRIPTION
**Pull request by Funkegrace**

### CODE REVIEW

**Review by SOG-web — COMMENTED** [review]
Perfect but have not tested it locally, and let's wait for others to check it out also

**Review by SOG-web — CHANGES_REQUESTED** [review]
solve the conflit

**Review by osahonjonathan — COMMENTED** [review]
cool but it would be nice if you use the angular cli to generate the button component as the cli itself generates a css or scss file together

**Review by Motseki — COMMENTED** [review]
The button style and color are fine, however I recommend that you use the correct button labels so that I can know exactly which button is which.

**Comment by Motseki** [comment]
In the project "READ.md" read the and following **Code scaffolding** Run ng generate component component-name to generate a new component. You can also use ng generate directive | pipe | service | class | guard | interface | enum  |module. Since you are creating the component use the following CLI command: ng generate buttons and will great the buttons.component.ts, buttons.component.html, buttons.component.scss and buttons.component.spec.ts.

**Pull request merged**
